apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcisocial
  labels:
    app: dcisocial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcisocial
  template:
    metadata:
      labels:
        app: dcisocial
    spec:
      volumes:
        - name: crt-volume
          secret:
            secretName: dcisocial-certs-own          
      containers:
      - name: dcisocial
        image: docker.io/suneroenne/dcisocial:1.0.34
        ports:
        - containerPort: 8080
          name: http-dcisocial
        env:
        - name: AzureAd__ClientSecret
          valueFrom:
            secretKeyRef:
              name: dcisocial-secrets
              key: azureclientsecret
        - name: Identity__OwnCrtFile
          value: /crt-volume/tls.crt
        - name: Identity__ChangeSchemeToHttps
          value: "true"
        - name: Identity__OwnKeyFile
          value: /crt-volume/tls.key
        - name: Fortification__ClientCertificateFile
          value: /crt-volume/tls.crt
        - name: Fortification__ClientPrivateKeyFile
          value: /crt-volume/tls.key
        - name: AzureAd__CallbackPath
          value: /oauth2-signin
        - name: Logging__LogLevel__DCI.Social.Identity.Middleware.UrlRedirectRewriteMiddleWare
          value: Debug
        - name: UI__FOBUrl
          value: http://fob/

        volumeMounts:
                - name: crt-volume
                  readOnly: true
                  mountPath: "/crt-volume"              
