apiVersion: apps/v1
kind: Deployment
metadata:
  name: fob
  labels:
    app: fob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fob
  template:
    metadata:
      labels:
        app: fob
    spec:
      volumes:
        - name: hq-crt-volume
          secret:
            secretName: fob-certs-hq          
        - name: social-crt-volume
          secret:
            secretName: fob-certs-social


      containers:
      - name: fob
        image: docker.io/suneroenne/dcifob:1.0.18
        ports:
        - containerPort: 8080
          name: http-fob
        env:
        - name: Fortification__TrustedCertificateFile
          value: /hq-crt-volume/tls.crt
        - name: Fortification__ClientCertificateFile
          value: /social-crt-volume/tls.crt

        volumeMounts:
                - name: hq-crt-volume
                  readOnly: true
                  mountPath: "/hq-crt-volume"              
                - name: social-crt-volume
                  readOnly: true
                  mountPath: "/social-crt-volume"              
          
