apiVersion: v1
kind: Service
metadata:
  name: fob
spec:
  type: NodePort
  selector:
    app: fob
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: http-fob
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30031
      name: svc-fob
