version: 2
plan:
  project-key: SI
  name: DCI.Social
  key: DCISOC

variables:
  Version: '1.0.${bamboo.buildNumber}'

stages:
  - BuildTestPublish:
    - Build

Build:
  key: DCISOCBUILD
  tasks:
  - clean
  - artifact-download:
      source-plan: TEM-SCRIP
      artifacts:
      - name: Scripts
        destination: Scripts
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Move_All_To_Source_Folder.ps1
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Nuget_Restore.ps1
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Build_Core.ps1 
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Solution_DotNetPack.ps1 -packageFeatureBranches
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Nuget_Publish.ps1 -source itcm_nuget -nugetDir .\Nuget 
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\ReplaceProjectWithPackageReferences.ps1 -searchString "DCI.Social.Domain" 
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\ReplaceProjectWithPackageReferences.ps1 -searchString "DCI.Social.Application" 
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\ReplaceProjectWithPackageReferences.ps1 -searchString "DCI.Social.Fortification" 
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\ReplaceProjectWithPackageReferences.ps1 -searchString "DCI.Social.Messages" 
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\RemoveProjectsFromSlnFile.ps1 -searchString "DCI.Social.Domain"
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\RemoveProjectsFromSlnFile.ps1 -searchString "DCI.Social.Application"
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\RemoveProjectsFromSlnFile.ps1 -searchString "DCI.Social.Fortification"
  - script: powershell.exe -ExecutionPolicy ByPass -file Source\\RemoveProjectsFromSlnFile.ps1 -searchString "DCI.Social.Messages"
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Solution_Package.ps1 -outputDir ".\Source" 
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Nuget_Publish.ps1 -source itcm_templates -nugetDir .\Source 
  - script: powershell.exe -ExecutionPolicy ByPass -file Scripts\\Git_Tag.ps1 
  requirements:
  - system.git.executable
  - system.builder.command.Nuget
  - system.builder.msbuild.MsBuild 2019
  - system.builder.command.OctopusCli
